version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: academic-net-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: academic-netDB
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE

  app:
    image: javagroup/academicnet:v1
    container_name: academicnet_app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/academic-netDB
    ports:
      - "9090:8080" # host:container
